# Generated by Django 4.1 on 2022-08-31 06:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_user', models.CharField(max_length=255)),
                ('created_user_id', models.IntegerField()),
                ('updated_user', models.CharField(max_length=255)),
                ('updated_user_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('usage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=999)),
                ('professional', models.BooleanField(default=False)),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name': 'VERBOSE NOT SET',
                'verbose_name_plural': 'VERBOSE PLURAL NOT SET',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_user', models.CharField(max_length=255)),
                ('created_user_id', models.IntegerField()),
                ('updated_user', models.CharField(max_length=255)),
                ('updated_user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'VERBOSE NOT SET',
                'verbose_name_plural': 'VERBOSE PLURAL NOT SET',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_user', models.CharField(max_length=255)),
                ('created_user_id', models.IntegerField()),
                ('updated_user', models.CharField(max_length=255)),
                ('updated_user_id', models.IntegerField()),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_type', models.CharField(choices=[('Miles', 'MILES'), ('Hours', 'HOURS')], max_length=255)),
                ('operation_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('miles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.vehicletypes')),
            ],
            options={
                'verbose_name': 'VERBOSE NOT SET',
                'verbose_name_plural': 'VERBOSE PLURAL NOT SET',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_user', models.CharField(max_length=255)),
                ('created_user_id', models.IntegerField()),
                ('updated_user', models.CharField(max_length=255)),
                ('updated_user_id', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('allowed_types', models.ManyToManyField(to='maintenance.vehicletypes')),
            ],
            options={
                'verbose_name': 'VERBOSE NOT SET',
                'verbose_name_plural': 'VERBOSE PLURAL NOT SET',
                'abstract': False,
            },
        ),
    ]
